export const ACTIONS = {
  FETCH_PALAVRA: 'FETCH_PALAVRA',
  TENTATIVA: 'TENTATIVA',

  INICIAR_TEMPO: 'INICIAR_TEMPO',
  PARAR_TEMPO: 'PARAR_TEMPO',
  CARREGAR_PROGRESSO: 'CARREGAR_PROGRESSO',
  LIMPAR_PROGRESSO: 'LIMPAR_PROGRESSO',
  TENTATIVA_TOTAL: 'TENTATIVA_TOTAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
};

export const MUTATIONS = {
  SET_PALAVRA: 'SET_PALAVRA',
  ERRO_TENTATIVA: 'ERRO_TENTATIVA',
  ACERTO_TENTATIVA: 'ACERTO_TENTATIVA',

  DEFINIR_TEMPO_INTERVAL: 'DEFINIR_TEMPO_INTERVAL',
  DEFINIR_TEMPO: 'DEFINIR_TEMPO',
  INCREMENTAR_TEMPO: 'INCREMENTAR_TEMPO',
  DEFINIR_PROGRESSO: 'DEFINIR_PROGRESSO',
  ACERTO_PALAVRA: 'ACERTO_PALAVRA',
  DEFINIR_NOME: 'DEFINIR_NOME',
  DEFINIR_MODAL: 'DEFINIR_MODAL',
  DEFINIR_RANKING: 'DEFINIR_RANKING',
};
