export const ACTIONS = {
  FETCH_PALAVRA: 'FETCH_PALAVRA',
  TENTATIVA: 'TENTATIVA',
  TENTATIVATOTAL: 'TENTATIVATOTAL',
};

export const MUTATIONS = {
  SET_PALAVRA: 'SET_PALAVRA',
  ERRO_TENTATIVA: 'ERRO_TENTATIVA',
  ACERTO_TENTATIVA: 'ACERTO_TENTATIVA',
  ACERTO_PALAVRA: 'ACERTO_PALAVRA',
};
